# Generated by Django 2.2.6 on 2019-10-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='menu',
            field=models.ManyToManyField(related_name='platMenu', to='resto.Menu'),
        ),
    ]
