# Generated by Django 2.2.6 on 2019-10-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fontion', models.CharField(max_length=255)),
                ('image', models.ImageField(default='useravatar.png', upload_to='MasterChef/')),
                ('fb_link', models.URLField(blank=True)),
                ('tw_link', models.URLField(blank=True)),
                ('g_link', models.URLField(blank=True)),
                ('insta_link', models.URLField(blank=True)),
            ],
        ),
    ]
