# Generated by Django 2.2.6 on 2019-10-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainConf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heure_travail',
            name='ferme',
            field=models.BooleanField(default=False),
        ),
    ]
